spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.warehouse: debug
